title: paiv
description: dev blog
baseurl: /blog
url: https://paiv.github.io

twitter_username: pavelivashkov
github_username:  paiv

markdown: kramdown

timezone: UTC
date_format: '%Y-%m-%d %H:%M'

defaults:
  -
    values:
      show_index: true
  -
    scope:
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - tools
