title: paiv
description: pavlo ivashkov dev blog
baseurl: /blog
url: https://paiv.github.io

twitter_username: pavelivashkov
github_username:  paiv
stackoverflow_username: paiv

markdown: kramdown

timezone: UTC
date_format: '%Y-%m-%d %H:%M'
future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

remote_theme: minima
minima:
  skin: auto

defaults:
  -
    values:
      show_index: true
      author: Pavlo Ivashkov
  -
    scope:
      type: posts
    values:
      layout: blogpost

exclude:
  - README.md
  - tools
