source 'https://rubygems.org'

gem 'jekyll', '3.10.0'
gem 'jekyll-remote-theme', '0.4.3'
gem 'kramdown-parser-gfm', '1.1.0'
gem 'minima', :git => 'https://github.com/jekyll/minima.git'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
end
