source 'https://rubygems.org'

# https://pages.github.com/versions/
gem 'jekyll', '3.10.0'
gem 'kramdown-parser-gfm', '1.1.0'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem 'jekyll-remote-theme', '0.4.3'
  gem 'jekyll-seo-tag', '2.8.0'
end
